base_url = "https://donabe8898.dev"
title = "donabe"
description="The front page of donabeeeeee"
default_language = "ja"
generate_feed = true
feed_filename = "rss.xml"
theme = "anemone"
compile_sass=true
minify_html = true



highlight_theme = "axar"
build_search_index = false
taxonomies = [
    {name = "tags", feed = true},
]


[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"


[extra]
author="donabe"
display_author = true

full_width = false
favicon = "/images/favicon.ico"
header_nav = [
	{url = "/", name_ja = "/home/"},
    {url = "/about", name_ja = "/about/"},
    {url = "/blog", name_ja = "/blog/" },
    {url = "/contents", name_ja = "/contents/"},
    {url = "/links" , name_ja = "/links/"}
]
default_theme = "dark"
list_pages = false
twitter_card = true

enable_katex = true
disqus = { enabled=false, short_name="donalog" }

