base_url = "https://donabe8898.dev"
title = "donabe"
description="The front page of donabeeeeee"
default_language = "ja"
generate_feed = true
feed_filename = "rss.xml"
theme = "zerm"
compile_sass=true

highlight_theme = "axar"
build_search_index = false
taxonomies = [
           {name = "tags", feed = true},
           {name = "categories", feed = true},
]
[markdown]
highlight_code = true
[extra]
author="donabe"
show_author = false
show_categories = true
show_tags = true
theme_color = "blue"
show_menu_items = 3
full_width = false
favicon = "/images/favicon.ico"
logo_text = "どな部屋"
main_menu = [
	{url="/profile/", name="プロフィール"},
	{url="/train/", name="乗鉄日記"},
	{url="/programming/", name="Programming"},
    {url="/link/", name="Ohter link"}
	{url="/pgp/", name="PGP", external=true},
	{url="https://github.com/donabe8898", name="GitHub", external=true},
	{url="https://donabe8898.dev", name="UNIX System V Release 4", external=true},

]
menu_more = "show more"
read_more="りーどモア"
read_other_posts = "もっと見る"
enable_katex = true
center = true
disqus = { enabled=false, short_name="donalog" }
