base_url = "/"
title = "donabe8898"
description = "The page of donabe8898"
default_language = "ja"
output_dir = "public"
compile_sass = true
build_search_index = false

theme = "zhuia"
generate_feed = true
feed_filename = "rss.xml"

taxonomies = [
           {name = "tags"},
           {name = "categories"},
]
[markdown]
highlight_code = true

[extra]
grid_size = "grid-lg"
author = "donabe"
show_author = true
show_tags = true
show_categories = true
read_more_prompt = "read more"
read_post_prompt = "read post"

hamburger_menu = true

main_menu = [
    {url="/about", name="about me"},
    {url="/tags/", name="tags"},
    {url="/categories/", name="categories"},          
]

social_links = [
    {url = "https://twitter.com/A10donabe", name = "twitter"},
    {url = "https://github.com/donabe8898", name = "github"},
    # {url = "", name = "instagram"},
    # {url = "", name = "facebook"},
]
[extra.sidebar]
active=true
text_snippet="æ›¸ãã“ã¨ç„¡ã„ã‹ã‚‰çŒ«ã§ã‚‚è¼‰ã›ã¦ãŠãã¾ã™ã­ã€€ğŸˆ < ï¾†ï½¬ï½°"

author_bio = "ã‚²ãƒ¼ãƒ ã¨ä¹—ã‚Šé‰„ãŒè¶£å‘³ã®æƒ…å ±ç³»å¤§å­¦ç”Ÿã€‚ã¤ã‚ˆããªã‚ŠãŸã„..."
author_avatar = "blueAGOOO.png"

tweets_by="A10donabe"

popular_tags=false
archive=false
related_posts=false

#========================

